Set Shell zsh

Output group.gif

Set Width 800
Set Height 500
Set FontSize 15
Set Padding 15

Set Theme "iceberg-dark"

Hide
Ctrl+L
Show

Sleep 200ms

Type "gotip -- -v -count=1"
Sleep 500ms
Enter

Sleep 500ms

Type "/"
Sleep 300ms

Type@200ms "input"
Enter
Sleep 300ms

Type@200ms "jjjj"
Sleep 500ms

Backspace
Sleep 300ms

Backspace
Sleep 1s

Type@200ms "jj"
Sleep 1s

Backspace
Sleep 1s

Enter

Sleep 3s